import { Card } from 'src/app/card';

export const firstClassLessons: Card[] = [
	{
		code: 'AIN101',
		title: 'Freshman Seminar',
		image: 'assets/ain101.jpg',
		website: null,
		exams: null,
		others: {
			// ! Not silinmiş.
			//'Notlar': 'https://drive.google.com/drive/u/1/folders/1DcsLe8BVMt_rtJTkODI81GUxYOWx9vbs',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['birinci sınıf semineri', 'ain 101'],
		createdAt: '2023-06-11',
		shown: false,
	},
	{
		code: 'BBM101',
		title: 'Introduction to Programming 1',
		image: 'assets/bbm101.jpg',
		website: 'https://web.cs.hacettepe.edu.tr/~bbm101/',
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/14j8FOWH9kIM_gGa9NG1xDppl8Yov0j34?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['programlamaya giriş 101'],
		createdAt: '2023-06-11',
	},
	{
		code: 'BBM102',
		title: 'Introduction to Programming 2',
		image: 'assets/bbm102.png',
		website: 'https://web.cs.hacettepe.edu.tr/~bbm102/',
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/1LhGeSaB-l1Rq0yruXKaEOamZI8SJeSbh?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['programlamaya giriş 102', 'programlamaya giriş 2'],
		createdAt: '2023-06-11',
	},
	{
		code: 'BBM103',
		title: 'Introduction to Programming Lab 1',
		image: 'assets/bbm103.jpg',
		website: 'https://web.cs.hacettepe.edu.tr/~bbm103/',
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/10DBoDJkyu4jZuZKK2C7jqPeO3mA0opQF?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['programlamaya giriş 1 laboratuvarı', 'programlamaya giriş 101 laboratuvarı', 'programlamaya giriş laboratuvar'],
		createdAt: '2023-06-11',
	},
	{
		code: 'BBM104',
		title: 'Introduction to Programming Lab 2',
		image: 'assets/bbm104.jpg',
		website: null,
		exams: null,
		others: {
			'Notlar -1': 'https://drive.google.com/drive/folders/1MVsRb28y1Cvb3eBt0daXQfXLFxCDWd2b?usp=drive_link',
			'Notlar -2': 'https://drive.google.com/drive/folders/1y_MELtzFTWNjQ1Y0rgqXRA_EIZEE3Oqz?usp=drive_link',
			'Notlar -3': 'https://drive.google.com/drive/folders/10DBoDJkyu4jZuZKK2C7jqPeO3mA0opQF?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['programlamaya giriş 2 laboratuvarı', 'programlamaya giriş 102 laboratuvarı', 'programlamaya giriş laboratuvar'],
		createdAt: '2023-06-11',
	},
	{
		code: 'BBM105',
		title: 'Introduction to Computer Engineering',
		image: 'assets/bbm105.jpg',
		website: null,
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/1JJWH7bb-OABYNMkE2iUNlsTuPRq_9Whl?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['bilgisayar mühendisliğine giriş 105'],
		createdAt: '2023-06-11',
	},
	{
		code: 'FİZ117',
		title: 'General Physics Lab',
		image: 'assets/fiz117.webp',
		website: null,
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/1YrMb8G7rOlunzyLu2i7mUDEwmh2jje7W?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['genel fizik laboratuvarı', 'fizik 117'],
		createdAt: '2023-06-11',
	},
	{
		code: 'FİZ137',
		title: 'Physics 1',
		image: 'assets/fiz137.jpg',
		website: null,
		exams: null,
		others: {
			'Notlar -1': 'https://drive.google.com/drive/folders/1jRz54iMRI-WbQR1bjNOlcgWEeDcrXW0i?usp=drive_link',
			'Notlar -2': 'https://drive.google.com/drive/folders/1E6Ja46ekvz-600a17y73NQBD7owN0ofl?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['fizik 137'],
		createdAt: '2023-06-11',
	},
	{
		code: 'FİZ138',
		title: 'Physics 2',
		image: 'assets/fiz138.jpg',
		website: null,
		exams: null,
		others: {
			'Notlar -1': 'https://drive.google.com/drive/folders/1MlhCK5NhUkM2GRLVt4t3xkWq80NnlnKm?usp=drive_link',
			'Notlar -2': 'https://drive.google.com/drive/folders/1iQ55N1VMSffew1F9YuLjiCuKWPKwwHOo?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['fizik 138'],
		createdAt: '2023-06-11',
	},
	{
		code: 'MAT123',
		title: 'Mathematics 1',
		image: 'assets/mat123.jpg',
		website: null,
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/1a-LiayX8GXunfl03wrXYRIbPQtlBuY64?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['matematik 123'],
		createdAt: '2023-06-11',
	},
	{
		code: 'MAT124',
		title: 'Mathematics 2',
		image: 'assets/mat124.jpg',
		website: null,
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/1TwlcPX0TFrEnQ20KBhY2VkP0KUnyySm8?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['matematik 124', 'matematik 2'],
		createdAt: '2023-06-11',
	},
	{
		code: 'BEB650',
		title: 'Basic Information and Communication Technologies',
		image: 'assets/beb650.jpg',
		website: null,
		exams: null,
		others: {
			// ! Notlar silinmiş.
			//'Notlar': 'https://docs.google.com/document/d/1PpSWnqtg545U-E0eaGTC7NsozCidow3y/edit?usp=drive_link&ouid=111043157051224304507&rtpof=true&sd=true',
			//'Çalışma Soruları': 'https://drive.google.com/file/d/1B8NqPKOop5jBw3foG-7sTIpnxgxI-G_9/view?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['temel bilgi ve iletişim teknolojileri', 'beb 650'],
		createdAt: '2023-06-11',
		shown: false,
	},
	{
		code: 'TKD103',
		title: 'Turkish 1',
		image: 'assets/tkd103.jpg',
		website: null,
		exams: null,
		others: {
			// ! Notlar silinmiş.
			//'Notlar': 'https://drive.google.com/file/d/1C2IFnU56Lad00J3U3_jmn3S5XBe0f7IY/view?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['türk dili 103', 'türkçe 1'],
		createdAt: '2023-06-11',
		shown: false,
	},
	{
		code: 'TKD104',
		title: 'Turkish 2',
		image: 'assets/tkd104.jpg',
		website: null,
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/file/d/1C28WJ3Y-zmV8HexCSP_OQsdxaau2KFIZ/view?usp=drive_link',
		},
		books: null,
		badges: ['first-class'],
		keywords: ['türk dili 104', 'türk dili 2', 'türkçe 2'],
		createdAt: '2023-06-11',
	},
];
