import { Card } from "src/app/card";

export const secondClassLessons: Card[] = [
	{
		code: 'BBM201',
		title: 'Data Structures',
		image: 'assets/bbm201.jpg',
		website: 'https://web.cs.hacettepe.edu.tr/~bbm201/',
		exams: 'https://drive.google.com/drive/folders/1nSPzDaHyKxiMA4kMIfFsKf9aJpdCplW4',
		others: {
			'BigO() CheatSheet': 'https://drive.google.com/file/d/1FK1rsINVakeJ55_B5b8ggculkorN3CFx/view',
		},
		books: {
			'ISO/IEC 9899 Committee Draft': 'https://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf',
			'Learning C With GDB': 'https://www.recurse.com/blog/5-learing-c-with-gdb',
			'C FAQ': 'https://c-faq.com/',
		},
		badges: ['second-class'],
		keywords: ['veri yapılarına giriş'],
		createdAt: '2019-02-14',
	},
	{
		code: 'BBM202',
		title: 'Algorithms',
		image: 'assets/bbm202.png',
		website: 'https://web.cs.hacettepe.edu.tr/~bbm202/',
		exams: 'https://drive.google.com/drive/folders/1bSNjkP5S-qnl-mZ8tWIMadkQLnuokMSc?usp=sharing',
		others: {
			'Özet': 'https://drive.google.com/file/d/1Hf2yyTXx17OEoXaX97dvbZADMDW95bry/view?usp=sharing',
		},
		books: null,
		badges: ['second-class'],
		keywords: ['algoritmalar'],
		createdAt: '2019-02-14',
	},
	{
		code: 'BBM205',
		title: 'Discrete Structures',
		image: 'assets/bbm205.jpg',
		website: 'https://web.cs.hacettepe.edu.tr/~bbm205/',
		exams: 'https://drive.google.com/drive/folders/1dT4wmxj4UZKmSmrkic4dJVqPr-EPk7QR?usp=sharing',
		others: {
			'CheatSheet': 'https://drive.google.com/file/d/1dZSYZjrIOyPNtYkcl3cT7RU_fCedQK6v/view?usp=sharing',
		},
		books: null,
		badges: ['second-class'],
		keywords: ['matematiksel yapılar'],
		createdAt: '2019-02-14',
	},
	{
		code: 'BBM231',
		title: 'Logic Design',
		image: 'assets/bbm231.jpg',
		website: 'https://web.cs.hacettepe.edu.tr/~bbm231/',
		exams: 'https://drive.google.com/drive/folders/1nSPzDaHyKxiMA4kMIfFsKf9aJpdCplW4?usp=sharing',
		others: {
			'BigO() CheatSheet': 'https://drive.google.com/file/d/1FK1rsINVakeJ55_B5b8ggculkorN3CFx/view?usp=sharing',
		},
		books: {
			'Digital Design, M. Morris Mano and Michael D. Ciletti, Prentice Hall.': 'https://profs.basu.ac.ir/abdoli/upload_file/digital%20design_morris%20mano_5th%20edition(722.3450.file_ref.3302.3611).pdf',
			'Digital Design and Computer Architecture, D. Harris, S. Harris, Morgan Kaufmann, 2007.': 'http://hron.fei.tuke.sk/~adam/cas/Digital%20Design%20and%20Computer%20Architecture%20(2nd%20Ed).pdf',
		},
		badges: ['second-class'],
		keywords: ['mantıksal tasarım'],
		createdAt: '2019-02-14',
	},
	{
		code: 'BBM234',
		title: 'Computer Organization',
		image: 'assets/bbm234.jpg',
		website: 'https://web.cs.hacettepe.edu.tr/~bbm234/',
		exams: 'https://drive.google.com/drive/folders/1E4Wdv1vQQY112Y8d9NkDwSC_4Tk8B4ar?usp=sharing',
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/1JZzHWy2o_Hei53xQ-bG0LDGRmsZv2xjb?usp=sharing',
			'Slaytlar': 'https://drive.google.com/drive/folders/1H_jZDYj2EI9MQsVzIljEK7PKC-z9TeZe?usp=sharing',
		},
		books: null,
		badges: ['second-class'],
		keywords: ['bilgisayar organizasyonu'],
		createdAt: '2019-02-14',
	},
	{
		code: 'MAT254',
		title: 'Linear Algebra',
		image: 'assets/mat254.png',
		website: null,
		exams: 'https://drive.google.com/drive/folders/1E4Wdv1vQQY112Y8d9NkDwSC_4Tk8B4ar?usp=sharing',
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/1-Q5FRaZ4NHJNy2hDYffeBV-YhqfWNoMk?usp=sharing',
			'Özet': 'https://drive.google.com/file/d/1WeBFGm3uwvtXkSd6wltqALHS0-eNBYRt/view?usp=sharing',
		},
		books: {
			'Lineer Cebir Ders Notları, Yrd. Doç. Dr. Hüseyin BILGIÇ': 'https://drive.google.com/file/d/1THRE1zyFtI7fU5CjEQpizlJrsgObd4Bt/view?usp=sharing',
		},
		badges: ['second-class'],
		keywords: ['doğrusal cebir', 'matematik'],
		createdAt: '2019-02-14',
	},
	{
		code: 'IST292',
		title: 'Probability',
		image: 'assets/ist292.jpg',
		website: null,
		exams: null,
		others: {
			'Notlar': 'https://drive.google.com/drive/folders/1lr5e05yDZIRMyiNutlxjE3uYoZKIzoqG?usp=sharing',
			'Slaytlar': 'https://drive.google.com/drive/folders/1doNNtwNnbPrLjZ9tCmyP4bc758UBLE-O?usp=sharing',
			'Özet': 'https://drive.google.com/file/d/1m_TOpsQ6DRemzMHGSXym438dlktQHZ0h/view?usp=sharing',
			'Tablolar': 'https://drive.google.com/file/d/1RIwk-XCeDkagc8fpOwCheYIXEVQhzKmU/view?usp=sharing'
		},
		books: null,
		badges: ['second-class'],
		keywords: ['olasılık', 'matematik'],
		createdAt: '2019-02-14',
	},
	{
		code: 'IST299',
		title: 'Statistics',
		image: 'assets/ist299.png',
		website: null,
		exams: null,
		others: {
			'Slaytlar': 'https://drive.google.com/drive/folders/1doNNtwNnbPrLjZ9tCmyP4bc758UBLE-O?usp=sharing',
			'Notlar': 'https://drive.google.com/drive/folders/14kxfxsFTTSU-Q3wQBbU8nYCW8exSwqy-?usp=sharing',
		},
		books: null,
		badges: ['second-class'],
		keywords: ['istatistik', 'matematik'],
		createdAt: '2019-02-14',
	},
];
