import { Card } from 'src/app/card';

export const technicals: Card[] = [
	{
		code: 'BBM402',
		title: 'Theory of Computation',
		image: 'assets/bbm402.jpg',
		website: 'https://web.cs.hacettepe.edu.tr/~ozkahya/classes/bbm402',
		exams: null,
		others: {
			'Quiz 1': 'https://drive.google.com/file/d/1cUOEg7TGVx6Q3ful-RXZCkjeeKK4n4HN/view?usp=sharing',
			'Quiz 2': 'https://drive.google.com/file/d/10MdG0PPoq_Oxbfd0YKmCGY-VOBWoBplU/view?usp=sharing',
			'Quiz 3': 'https://drive.google.com/file/d/1peyzRhhcyxvJLz7KSHTrgFsD0MYkirzc/view?usp=sharing',
			'Quiz 4': 'https://drive.google.com/file/d/1hU4bxax_D6GFLQHkYWlYXaTUfpHc7XtA/view?usp=sharing',
			'Midterm Özet': 'https://drive.google.com/file/d/1zLA0sfLg6_Dq_9L9SidLaCpu0r2-SbG4/view?usp=sharing',
		},
		books: {
			'Foundations of Computer Science': 'http://i.stanford.edu/~ullman/focs.html',
			'Theory of Computation & Automata Theory - Youtube Series': 'https://www.youtube.com/watch?v=58N2N7zJGrQ&list=PLBlnK6fEyqRgp46KUv4ZY69yXmpwKOIev',
		},
		badges: ['technicals'],
		keywords: ['hesaplama teorisi'],
		createdAt: '2019-02-19',
	},
	{
		code: 'BBM406',
		title: 'Fundamentals of Machine Learning',
		image: 'assets/bbm406.jpg',
		website: null,
		exams: null,
		others: null,
		books: {
			'Machine Learning Trends': 'https://drive.google.com/file/d/1GNMNDqwVUU_mmIMKmrTwars_eQJf-SWp/view?usp=sharing',
		},
		badges: ['technicals'],
		keywords: ['makine öğrenmesinin temelleri'],
		createdAt: '2019-02-19',
	},
	{
		code: 'BBM408',
		title: 'Algorithm Analysis',
		image: 'assets/bbm408.png',
		website: null,
		exams: null,
		others: {
			'MIT Exams': 'https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-design-and-analysis-of-algorithms-spring-2015/exams/',
			'Georgia Tech. Exam': 'https://www.cc.gatech.edu/~rpeng/CS3510_F17/Tests/F16ExamSol.pdf',
			'Oregon State Exam': 'http://web.engr.oregonstate.edu/~nayyeria/CS325/Fall16/hws/final-sol.pdf',
			'Algoritma Analizi - Şadi Evren ŞEKER': 'https://www.youtube.com/watch?v=3bhBo9YCTpo&list=PLh9ECzBB8tJPTWIUbZjHZMMGuZcpHUv5h',
			'Algorithm Analysis - Abdul BARi': 'https://www.youtube.com/watch?v=0IAPZzGSbME&list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O',
		},
		books: null,
		badges: ['technicals'],
		keywords: ['algoritma analizi'],
		createdAt: '2019-03-04',
	},
	{
		code: 'BBM410',
		title: 'Dynamic Systems',
		image: 'assets/bbm410.png',
		website: 'https://web.cs.hacettepe.edu.tr/~onderefe/bbm410/',
		exams: null,
		others: {
			'Linear Algebra Youtube Series': 'https://www.youtube.com/watch?v=ZK3O402wf1c&list=PLE7DDD91010BC51F8',
			'Differential Equations Youtube Series': 'https://www.youtube.com/watch?v=XDhJ8lVGbl8&list=PLEC88901EBADDD980',
		},
		books: {
			'Mehmet Önder Efe, "Otomatik Kontrol Sistemleri," Seçkin Yayıncılık, 2012.': 'https://www.kitapsec.com/Products/Otomatik-Kontrol-Sistemleri-2Baski-Seckin-Yayinlari-46484.html?gclid=Cj0KCQiA2L7jBRCBARIsAPeAsaM5wCA77bgJw55h8x4OHV-3el4xuNEn_4i2Zl_rEnc9FUVha3kpfZIaAnQaEALw_wcB',
			'David G. Luenberger, "Introduction to Dynamic Systems," John Wiley & Sons, 1979.': 'http://home.deib.polimi.it/guariso/BAC/Texts/Luenberger.pdf'
		},
		badges: ['technicals'],
		keywords: ['dinamik sistemler', 'matlab'],
		createdAt: '2019-02-22',
	},
	{
		code: 'BBM412',
		title: 'Computer Graphics',
		image: 'assets/bbm412.jpg',
		website: null,
		exams: null,
		others: {
			'Slaytlar': 'https://drive.google.com/drive/folders/1UO099xVulp0emYPj7NblA2vKJq1QWDos?usp=sharing',
			'OpenGL 4.1 Quick Reference Card': 'https://drive.google.com/file/d/1Uwbn1W0odEh6C0a3lsrHtLcMWYJwlBP-/view?usp=sharing',
			'Interactive Computer Graphics': 'https://drive.google.com/file/d/1vaQ09ejZOdcv_bre8YxodmTCPXoFdWF4/view?usp=sharing',
		},
		books: null,
		badges: ['technicals'],
		keywords: ['bilgisayar grafikleri', 'opengl', 'oyun geliştirme'],
		createdAt: '2019-02-14',
	},
	{
		code: 'BBM463',
		title: 'Information Security',
		image: 'assets/bbm463.jpg',
		website: null,
		exams: null,
		others: {
			'Slaytlar': 'https://drive.google.com/open?id=1RIj3I7DWPjDycCgY_nRHDQLy12s9EPz0',
		},
		books: null,
		badges: ['technicals'],
		keywords: ['bilgi güvenliği', 'kriptografi'],
		createdAt: '2019-02-14',
	},
	{
		code: 'BBM467',
		title: 'Data Intensive Applications',
		image: 'assets/bbm467.png',
		website: null,
		exams: null,
		others: {
			'Slaytlar': 'https://drive.google.com/open?id=1OSJ2neU_DmckzqE7IwV4_tnlT3w4UAIS',
			'Lab': 'https://drive.google.com/open?id=1Wg7Mg1xxlaJeS0e2e9nAN6uKGczrNLd0',
		},
		books: null,
		badges: ['technicals'],
		keywords: ['veri yoğunluklu uygulamalar', 'veri tabanı'],
		createdAt: '2020-03-08',
	},
	{
		code: 'BBM471',
		title: 'Data Management Systems',
		image: 'assets/bbm471.jpg',
		website: null,
		exams: null,
		others: {
			'Slaytlar': 'https://miro.medium.com/max/1080/1*XTlKxS6V_Kg9pb73el0ckg.jpeg',
		},
		books: null,
		badges: ['technicals'],
		keywords: ['veri yönetim sistemleri', 'veri tabanı yönetim sistemleri'],
		createdAt: '2020-03-08',
	},
	{
		code: 'BBM495',
		title: 'Introduction to Natural Language Processing',
		image: 'assets/bbm495.jpg',
		website: null,
		exams: null,
		others: {
			'Slaytlar': 'https://drive.google.com/open?id=1eyPvCtVD5QNFZO6j9XXq6O4qP9TTb9v4',
			'Lab': 'https://drive.google.com/open?id=18wXo1Wp8srJGuYCoFpBr7M1E6rhYZzXv',
		},
		books: null,
		badges: ['technicals'],
		keywords: ['doğal dil işleme', 'yapay zeka', 'makine öğrenmesi'],
		createdAt: '2020-03-08',
	},
];
